"""20220925181645 puffy_hill

Revision ID: 43fc549dacea
Revises: 7dda1641a129
Create Date: 2022-09-25 18:16:46.359569

"""
from alembic import op
import sqlalchemy as sa
import os


# revision identifiers, used by Alembic.
revision = '43fc549dacea'
down_revision = '7dda1641a129'
branch_labels = None
depends_on = None


def run_migration() -> bool:
    return os.getenv('MIGRATION_RUN_ALL', '0') != '0'


def upgrade() -> None:
    if not run_migration():
        return None
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contents_description'), 'contents', ['description'], unique=False)
    op.create_index(op.f('ix_contents_id'), 'contents', ['id'], unique=False)
    op.create_index(op.f('ix_contents_title'), 'contents', ['title'], unique=False)
    op.create_index(op.f('ix_contents_url'), 'contents', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    if not run_migration():
        return None
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contents_url'), table_name='contents')
    op.drop_index(op.f('ix_contents_title'), table_name='contents')
    op.drop_index(op.f('ix_contents_id'), table_name='contents')
    op.drop_index(op.f('ix_contents_description'), table_name='contents')
    op.drop_table('contents')
    # ### end Alembic commands ###
