"""20220925195523 powerful_wrath

Revision ID: eb368989c04b
Revises: 43fc549dacea
Create Date: 2022-09-25 19:55:29.343173

"""
from alembic import op
import sqlalchemy as sa
import os


# revision identifiers, used by Alembic.
revision = 'eb368989c04b'
down_revision = '43fc549dacea'
branch_labels = None
depends_on = None


def run_migration() -> bool:
    return os.getenv('MIGRATION_RUN_ALL', '0') != '0'


def upgrade() -> None:
    if not run_migration():
        return None
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('views',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('content_id', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_views_content_id'), 'views', ['content_id'], unique=False)
    op.create_index(op.f('ix_views_id'), 'views', ['id'], unique=False)
    op.create_index(op.f('ix_views_session_id'), 'views', ['session_id'], unique=False)
    op.create_index(op.f('ix_views_user_id'), 'views', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    if not run_migration():
        return None
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_views_user_id'), table_name='views')
    op.drop_index(op.f('ix_views_session_id'), table_name='views')
    op.drop_index(op.f('ix_views_id'), table_name='views')
    op.drop_index(op.f('ix_views_content_id'), table_name='views')
    op.drop_table('views')
    # ### end Alembic commands ###
