
version: 2

sources:
  - name: raw
    schema: sample
    database: sample

    freshness:
      warn_after:
        count: 12
        period: hour
      error_after: 
        count: 24
        period: hour

    loaded_at_field: _airbyte_normalized_at

    tables:

      - name: raw_views
        identifier: views

      - name: raw_contents
        identifier: contents

      - name: raw_users
        identifier: users

models:

  - name: global_content_views
    description: |
      # Global content view counts
    columns:
      - name: id
        description: Id of the content
        tests:
          - unique
          - not_null
      - name: global_view_count
        description: Global view count for a single content
      